services:
  oracle-free:
    image: container-registry.oracle.com/database/free:23.5.0.0-lite
    container_name: oracle-free
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: 1234
    volumes:
      - ~/podman-stuff/oracle/scripts:/opt/oracle/scripts/startup
      - oracle-data:/opt/oracle/oradata
    deploy:
      resources:
        limits:
          memory: 4G

volumes:
  oracle-data:
